version: '3.7'

services:
  python_app:
    build:
      context: home_python
    ports:
      - 7001:443
    volumes:
      - ./home_python/src:/app/src
      - ./certs:/app/certs
    env_file:
      - home_python/deploy/.env-local

